---
- import_playbook: deploy-frontend.yml
- import_playbook: deploy-backend.yml

- name: Setup services and webserver configs
  hosts: webservers
  gather_facts: true
  become: yes
  tasks:
    - name: Setup services
      include_tasks: tasks/setup-services.yml

    # Please confirm: appears above task `setup-services` restarts api service already. Consider removing this and just `include_playbook` for above task
    - name: Restart API service
      systemd:
        state: restarted
        name: "{{ be_api_service_name }}" 

    - name: Restart worker service
      systemd:
        state: restarted
        name: "{{ be_worker_service_name }}"
      # when: be_clone.changed

    - name: Restart open graph app service
      systemd:
        state: restarted
        name: "{{ be_og_app_service_name }}"
      # when: be_clone.changed