---
- import_playbook: deploy-frontend.yml
- import_playbook: deploy-backend.yml

- name: Setup services and webserver configs
  hosts: webservers
  gather_facts: true
  become: yes
  tasks:
    - name: Setup services
      include_tasks: tasks/setup-services.yml

    # Please confirm: appears above task `setup-services` restarts api service already. Consider removing this and just `include_playbook` for above task
    - name: Restart API service
      systemd:
        state: restarted
        name: "{{ be_api_service_name }}" 

    # - name: Restart celery worker service
    #   systemd:
    #     state: restarted
    #     name: "{{ be_celery_service_name }}"
    #   become: yes
    #   # when: be_clone.changed

    # - name: Restart celerybeat service
    #   systemd:
    #     state: restarted
    #     name: "{{ be_celerybeat_service_name }}"
    #   become: yes
    #   # when: be_clone.changed