env_name: production
admin_email: "{{ vault_admin_email }}"
repo_name: michaeltoohig/bilolok

domain: bilolok.com
domain_api: api.bilolok.com
domain_upload: upload.bilolok.com
domain_image: image.bilolok.com
domain_video: video.bilolok.com

mj_relayhost: in-v3.mailjet.com
mj_relayhost_port: 587
mj_apikey_public: "{{ vault_mj_apikey_public }}"
mj_apikey_private: "{{ vault_mj_apikey_private }}"

docker_service_name: docker-compose@bilolok.service

db_container_name: "{{ vault_db_container_name }}"
db_user: "{{ vault_db_user }}"
db_name: "{{ vault_db_name }}"

root_directory: /var/www/bilolok.com
repo_directory: "{{ root_directory }}/app"
data_directory: "{{ root_directory }}/data"

be_worker_service_name: bilolok-worker.service
be_api_service_name: api.bilolok.service
be_api_service_port: 5000
be_og_app_service_name: bilolok-og-app.service
be_og_app_service_port: 5001
be_remote_directory: "{{ repo_directory }}/backend/app"


fe_local_directory: ../frontend
fe_remote_directory: "{{ root_directory }}/www"

upload_service_port: 8070
image_service_port: 8888

video_remote_directory: "{{ data_directory }}/videos"